variables:
  azureSubscription: 'EmTech_ChatViatris_Prod'
  resourceGroupName: 'emtech-emt-itapp-d2-rg-ngxp-prd'
  WebAppName: 'emtfrt-emt-itapp-d2-wa-ngxp-prd'
  REACT_APP_GUARDRAIL_URL: 'https://emtgrd-emt-itapp-d2-wa-ngxp-prod.azurewebsites.net/'